package com.theaigames.game.warlight2.map;

import org.json.JSONObject;

public class Settings {
    // note: default settings are similar to "1v1 SmallEarth - one wasteland"

    private final int DEFAULT_NUM_STARTING_TERRITORIES = 2;

    private final int DEFAULT_BASE_ARMIES_PER_TURN = 5;
    private final int DEFAULT_INITIAL_PLAYER_ARMIES = 4;
    private final int DEFAULT_NEUTRAL_ARMIES = 2;
    private final int DEFAULT_NEUTRAL_ARMIES_IN_DISTRIBUTION = 4;  // TODO: not used yet

    private final int DEFAULT_WASTELAND_SIZE = 10;
    private final int DEFAULT_NUMBER_OF_WASTELANDS = 1;

    public enum DistributionMode { RANDOM_WARLORD, FULL };  // TODO: random_cities, warlords, cities
    public final DistributionMode DEFAULT_DISTRIBUTION_MODE = DistributionMode.RANDOM_WARLORD;

    public enum MoveOrder { CYCLE, RANDOM };  // note: for bot's purposes cycle and no-luck cycle are the same
    private final MoveOrder DEFAULT_MOVE_ORDER = MoveOrder.CYCLE;  // TODO: other modes not supported yet

    private final double DEFAULT_DEFENSIVE_KILL_RATIO = 0.7;
    private final double DEFAULT_OFFENSIVE_KILL_RATIO = 0.6;
    private final double DEFAULT_LUCK_MODIFIER = 0;

    public enum RoundingMode { STRAIGHT_ROUND, WEIGHTED_RANDOM };
    private final RoundingMode DEFAULT_ROUNDING_MODE = RoundingMode.WEIGHTED_RANDOM; //STRAIGHT_ROUND;

    private final long DEFAULT_TIMEBANK_MAX = 10000l;
    private final long DEFAULT_INITIAL_TIMEBANK = DEFAULT_TIMEBANK_MAX;
    private final long DEFAULT_EXTRA_TIME_PER_MOVE = 500l;  // 5 seconds

    // TODO: fog, one-army-stand-guard, multi-attack, bonus-army-per-territory
    // TODO: commanders, local deployments, no-split
    // TODO: cards (reinf, airlift, sanction, spy, bomb, order priority/delay)
    // TODO: team games - any settings?

    JSONObject settingsJSON;

    public Settings() {
        this.settingsJSON = new JSONObject();
    }

    // TODO: improve performance, parse JSON on load and not when a value is needed
    public Settings(JSONObject settingsJSON) {
        this.settingsJSON = settingsJSON;
    }

    public int getNumberOfStartingTerritories() {
        return settingsJSON.optInt("TerritoryLimit", this.DEFAULT_NUM_STARTING_TERRITORIES);
    }

    public int getBaseArmiesPerTurn() {
        return settingsJSON.optInt("MinimumArmyBonus", this.DEFAULT_BASE_ARMIES_PER_TURN);
    }

    public int getInitilPlayerArmies() {
        return settingsJSON.optInt("InitialPlayerArmiesPerTerritory", this.DEFAULT_INITIAL_PLAYER_ARMIES);
    }

    public int getNeutralArmies() {
        return settingsJSON.optInt("InitialNonDistributionArmies", this.DEFAULT_NEUTRAL_ARMIES);
    }

    public int getNeutralArmiesInDistribution() {
        return settingsJSON.optInt("InitialNeutralsInDistribution", this.DEFAULT_NEUTRAL_ARMIES_IN_DISTRIBUTION);
    }

    public int getWastelandSize() {
        return this.DEFAULT_WASTELAND_SIZE;
    }

    public int getNumberOfWastelands() {
        return this.DEFAULT_NUMBER_OF_WASTELANDS;
    }

    // random warlords/cities: this will generally mean that Superbonuses will have one territory for each minor bonus,
    // plus an additional territory; included in distribution for warlords, and excluded in distribution for cities.
    public DistributionMode getDistributionMode() {
        return this.DEFAULT_DISTRIBUTION_MODE;
    }

    public MoveOrder getMoveOrder() {
        return this.DEFAULT_MOVE_ORDER;
    }

    public double getDefensiveKillRatio() {
        return this.DEFAULT_DEFENSIVE_KILL_RATIO;
    }

    public double getOffensiveKillRatio() {
        return this.DEFAULT_OFFENSIVE_KILL_RATIO;
    }

    public double getLuckModifier() {
        return this.DEFAULT_LUCK_MODIFIER;
    }

    public RoundingMode getRoundingMode() {
        return this.DEFAULT_ROUNDING_MODE;
    }

    public long getInitialTimebank() {
        return this.DEFAULT_INITIAL_TIMEBANK;
    }

    public long getMaxTimebank() {
        return this.DEFAULT_TIMEBANK_MAX;
    }

    public long getExtraTimePerMove() {
        return this.DEFAULT_EXTRA_TIME_PER_MOVE;
    }

    /**
     * Sample settings JSON, as generated by the WarZone server:
     {
        "OffensiveKillRate" : 60,
        "DefensiveKillRate" : 70,
        "LuckModifier" : 0.18,             // no luck : 0.0
        "RoundingMode" : "StraightRound",  // or "WeightedRandom"

        "TerritoryLimit" : 3,
        "DistributionMode" : -1,           // -1 == random warlords (one region per bonus), -3 = full
        "InitialPlayerArmiesPerTerritory" : 5,
        "InitialNonDistributionArmies" : 2,
        "InitialNeutralsInDistribution" : 4,
        "Wastelands" : {
          "NumberOfWastelands" : 7,
          "WastelandSize" : 10
        },
        "MinimumArmyBonus" : 5,
        "BonusArmyPer" : 0,

        "MoveOrder" : "Cycle"    // "Random",
        "Fog" : "Foggy",         // "NoFog", "LightFog,", "ModerateFog", "Foggy", "VeryFoggy", "ExtremeFog"
        "MultiAttack" : false,
        "Commanders" : false,
        "OneArmyStandsGuard" : true,
        "DirectBoot" : 4320.0,   // in minutes
        "LocalDeployments" : false,
        "NoSplit" : false,

        "ReinforcementCard" : {
          "NumPieces" : 4,
          "InitialPieces" : 0,
          "MinimumPiecesPerTurn" : 1,
          "Weight" : 1.0,
          "Mode" : 0,
          "FixedArmies" : 5
        },
        "SpyCard" : "none",
        "OrderPriorityCard" : {
          "NumPieces" : 6,
          "InitialPieces" : 0,
          "MinimumPiecesPerTurn" : 1,
          "Weight" : 1.0
        },
        "OrderDelayCard" : {
          "NumPieces" : 5,
          "InitialPieces" : 0,
          "MinimumPiecesPerTurn" : 1,
          "Weight" : 1.0
        },
        "AirliftCard" : "none",
        "SanctionsCard" : "none",
        "ReconnaissanceCard" : "none",
        "SurveillanceCard" : "none",
        "BlockadeCard" : "none",
        "BombCard" : "none",
        "MaxCardsHold" : 3,
        "NumberOfCardsToReceiveEachTurn" : 3
     }
     */
}
